"""initial database schema

Revision ID: d1b7887b63eb
Revises: 
Create Date: 2026-08-29 16:00:18.043795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1b7887b63eb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_gaps',
    sa.Column('gap_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('importance', sa.Text(), nullable=False),
    sa.Column('future_direction', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('gap_id')
    )
    op.create_index(op.f('ix_research_gaps_gap_id'), 'research_gaps', ['gap_id'], unique=False)
    op.create_table('retrieval_sessions',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('expanded_query', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('total_papers', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_retrieval_sessions_session_id'), 'retrieval_sessions', ['session_id'], unique=False)
    op.create_table('comparisons',
    sa.Column('comparison_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('similarities', sa.Text(), nullable=False),
    sa.Column('differences', sa.Text(), nullable=False),
    sa.Column('contradictions', sa.Text(), nullable=False),
    sa.Column('research_trends', sa.Text(), nullable=False),
    sa.Column('research_clusters', sa.Text(), nullable=False),
    sa.Column('comparison_summary', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['retrieval_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('comparison_id')
    )
    op.create_index(op.f('ix_comparisons_comparison_id'), 'comparisons', ['comparison_id'], unique=False)
    op.create_table('confidence_scores',
    sa.Column('confidence_id', sa.Integer(), nullable=False),
    sa.Column('gap_id', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gap_id'], ['research_gaps.gap_id'], ),
    sa.PrimaryKeyConstraint('confidence_id'),
    sa.UniqueConstraint('gap_id')
    )
    op.create_index(op.f('ix_confidence_scores_confidence_id'), 'confidence_scores', ['confidence_id'], unique=False)
    op.create_table('papers',
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('authors', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('journal', sa.String(length=255), nullable=True),
    sa.Column('pdf_path', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('download_status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['retrieval_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('paper_id'),
    sa.UniqueConstraint('doi')
    )
    op.create_index(op.f('ix_papers_paper_id'), 'papers', ['paper_id'], unique=False)
    op.create_table('session_processing_status',
    sa.Column('session_status_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('comparison_done', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('gap_discovery_done', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('validation_done', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('confidence_done', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['retrieval_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('session_status_id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index(op.f('ix_session_processing_status_session_status_id'), 'session_processing_status', ['session_status_id'], unique=False)
    op.create_table('validations',
    sa.Column('validation_id', sa.Integer(), nullable=False),
    sa.Column('gap_id', sa.Integer(), nullable=False),
    sa.Column('validation_result', sa.String(length=20), nullable=False),
    sa.Column('supporting_reason', sa.Text(), nullable=False),
    sa.Column('contradicting_reason', sa.Text(), nullable=False),
    sa.Column('validated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gap_id'], ['research_gaps.gap_id'], ),
    sa.PrimaryKeyConstraint('validation_id'),
    sa.UniqueConstraint('gap_id')
    )
    op.create_index(op.f('ix_validations_validation_id'), 'validations', ['validation_id'], unique=False)
    op.create_table('agent_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=True),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('execution_time', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['retrieval_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_agent_logs_log_id'), 'agent_logs', ['log_id'], unique=False)
    op.create_table('comparison_members',
    sa.Column('comparison_member_id', sa.Integer(), nullable=False),
    sa.Column('comparison_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comparison_id'], ['comparisons.comparison_id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], ),
    sa.PrimaryKeyConstraint('comparison_member_id')
    )
    op.create_index(op.f('ix_comparison_members_comparison_member_id'), 'comparison_members', ['comparison_member_id'], unique=False)
    op.create_table('gap_papers',
    sa.Column('gap_paper_id', sa.Integer(), nullable=False),
    sa.Column('gap_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gap_id'], ['research_gaps.gap_id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], ),
    sa.PrimaryKeyConstraint('gap_paper_id')
    )
    op.create_index(op.f('ix_gap_papers_gap_paper_id'), 'gap_papers', ['gap_paper_id'], unique=False)
    op.create_table('methodologies',
    sa.Column('methodology_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('dataset', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('preprocessing', sa.Text(), nullable=False),
    sa.Column('evaluation_metrics', sa.Text(), nullable=False),
    sa.Column('limitations', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], ),
    sa.PrimaryKeyConstraint('methodology_id'),
    sa.UniqueConstraint('paper_id')
    )
    op.create_index(op.f('ix_methodologies_methodology_id'), 'methodologies', ['methodology_id'], unique=False)
    op.create_table('paper_chunks',
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('chunk_number', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=100), nullable=True),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding_id', sa.String(length=100), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], ),
    sa.PrimaryKeyConstraint('chunk_id'),
    sa.UniqueConstraint('embedding_id')
    )
    op.create_index(op.f('ix_paper_chunks_chunk_id'), 'paper_chunks', ['chunk_id'], unique=False)
    op.create_table('processing_status',
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('downloaded', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('parsed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('chunked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('embedded', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('summarized', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('evidence_done', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('methodology_done', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], ),
    sa.PrimaryKeyConstraint('status_id'),
    sa.UniqueConstraint('paper_id')
    )
    op.create_index(op.f('ix_processing_status_status_id'), 'processing_status', ['status_id'], unique=False)
    op.create_table('summaries',
    sa.Column('summary_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=False),
    sa.Column('research_problem', sa.Text(), nullable=True),
    sa.Column('key_contributions', sa.Text(), nullable=True),
    sa.Column('methodology_summary', sa.Text(), nullable=True),
    sa.Column('main_findings', sa.Text(), nullable=True),
    sa.Column('limitations', sa.Text(), nullable=True),
    sa.Column('future_work', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], ),
    sa.PrimaryKeyConstraint('summary_id'),
    sa.UniqueConstraint('paper_id')
    )
    op.create_index(op.f('ix_summaries_summary_id'), 'summaries', ['summary_id'], unique=False)
    op.create_table('evidence',
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('supporting_text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['paper_chunks.chunk_id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], ),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_index(op.f('ix_evidence_evidence_id'), 'evidence', ['evidence_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_evidence_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_summaries_summary_id'), table_name='summaries')
    op.drop_table('summaries')
    op.drop_index(op.f('ix_processing_status_status_id'), table_name='processing_status')
    op.drop_table('processing_status')
    op.drop_index(op.f('ix_paper_chunks_chunk_id'), table_name='paper_chunks')
    op.drop_table('paper_chunks')
    op.drop_index(op.f('ix_methodologies_methodology_id'), table_name='methodologies')
    op.drop_table('methodologies')
    op.drop_index(op.f('ix_gap_papers_gap_paper_id'), table_name='gap_papers')
    op.drop_table('gap_papers')
    op.drop_index(op.f('ix_comparison_members_comparison_member_id'), table_name='comparison_members')
    op.drop_table('comparison_members')
    op.drop_index(op.f('ix_agent_logs_log_id'), table_name='agent_logs')
    op.drop_table('agent_logs')
    op.drop_index(op.f('ix_validations_validation_id'), table_name='validations')
    op.drop_table('validations')
    op.drop_index(op.f('ix_session_processing_status_session_status_id'), table_name='session_processing_status')
    op.drop_table('session_processing_status')
    op.drop_index(op.f('ix_papers_paper_id'), table_name='papers')
    op.drop_table('papers')
    op.drop_index(op.f('ix_confidence_scores_confidence_id'), table_name='confidence_scores')
    op.drop_table('confidence_scores')
    op.drop_index(op.f('ix_comparisons_comparison_id'), table_name='comparisons')
    op.drop_table('comparisons')
    op.drop_index(op.f('ix_retrieval_sessions_session_id'), table_name='retrieval_sessions')
    op.drop_table('retrieval_sessions')
    op.drop_index(op.f('ix_research_gaps_gap_id'), table_name='research_gaps')
    op.drop_table('research_gaps')
    # ### end Alembic commands ###
